# Python releases to test
language: python
python:
  - 2.7
# Django releases
env:
  - DJANGO_VERSION=Django==1.6.2

# Package installation
install:
  - pip install --use-mirrors $DJANGO_VERSION
  - pip install pep8
  - python setup.py install
# Run the tests
script:
  - pep8 bulkimport
  - python quicktest.py bulkimport